"""empty message

Revision ID: 00adb9d1ad92
Revises: 43f9c84fb85f
Create Date: 2024-07-12 14:09:14.740150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00adb9d1ad92'
down_revision = '43f9c84fb85f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('avatar_path', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('product_id', sa.String(length=64), nullable=True))
        batch_op.create_foreign_key("Name", 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('product_id')
        batch_op.drop_column('description')
        batch_op.drop_column('avatar_path')
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###
