"""empty message

Revision ID: 38e44233d6b1
Revises: 00adb9d1ad92
Create Date: 2024-07-12 15:39:07.530511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38e44233d6b1'
down_revision = '00adb9d1ad92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_measure', sa.Enum(('tonne', 'kg', 'g', 'l', 'ml', 'pcs')), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('unit_measure')

    # ### end Alembic commands ###
