"""Migrations

Revision ID: a7c080e162d9
Revises: 89d98c56986d
Create Date: 2024-07-07 18:54:12.285098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c080e162d9'
down_revision = '89d98c56986d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('retail_price')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('location')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retail_price', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
